apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:                 # specify the set of pods that this deployment object will supposed to control
    matchLabels:
      component: server     # component is a kind of label. It can be any wor (like PartOfApp etc.)
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name:  server
          image: hayrettinm/multi-server
          ports: 
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:                                  # get the value for this env variable from some conf that we're going to put in here.
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
